ram:
  value_mb: 163840
rom:
  nums: 1
  value_mb_each: 2024000
  min_read_v_mbs: 500
  min_write_v_mbs: 500
ports:
  ethernets:
    - name: enp1s0
      ip: 192.168.0.101
      port: 8765
    - name: enp2s0
      ip: 192.168.0.102
      port: 8765
    - name: enp3s0
      ip: 193.168.0.101
      port: 8765
    - name: enp4s0
      ip: 193.168.0.101
      port: 8765
  packets_loss: 0
  com:
    - /dev/ttyS0
    - /dev/ttyS1
usb_flash:
  mount_point: /mnt/usb
  filename: test.txt
stress:
  max_heat: 85
  gradient: 40
  duration: 10m
optional_flags:
  ports: true
  usb_flash: true
  stress: true
